name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Ejecutar cuando haya cambios en la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Entorno donde se ejecuta el trabajo

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Loguearse en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Tu usuario de Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Tu token de Docker Hub

      # 4. Construir y subir la imagen a Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: daymler83/projectmimunido:latest


